# Generated by Django 4.0.6 on 2022-07-04 21:39

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('contacts', '0002_alter_contact_phone_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_name',
            field=models.CharField(help_text='Name of contact', max_length=50, verbose_name='Contact name'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone_value',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='Phone number of contact', max_length=13,
                                                                 region=None, verbose_name='Phone number'),
        ),
    ]
