# Generated by Django 4.0.6 on 2022-07-07 17:12

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('contacts', '0003_alter_contact_contact_name_alter_contact_phone_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone_value',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='Phone number of contact', max_length=13,
                                                                 region=None, unique=True, verbose_name='Phone number'),
        ),
    ]
