# Generated by Django 4.0.6 on 2022-07-08 17:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('contacts', '0004_alter_contact_phone_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='birthday',
            field=models.DateField(blank=True, help_text='Date of birth', null=True, verbose_name='Birthday'),
        ),
    ]
