# Generated by Django 4.0.6 on 2022-07-09 06:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('contacts', '0005_contact_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='contact_tags',
            field=models.CharField(blank=True, choices=[('family', 'Family'), ('job', 'Job'), ('friends', 'Friends'),
                                                        ('journey', 'Journey'), ('event', 'Event'),
                                                        ('university', 'University')], default='friends', max_length=40,
                                   null=True, verbose_name='Tags'),
        ),
    ]
