# Generated by Django 4.0.6 on 2022-07-09 08:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('contacts', '0006_contact_contact_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagsChoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='contact',
            name='contact_tags',
        ),
        migrations.AddField(
            model_name='contact',
            name='contact_tag',
            field=models.CharField(default='', help_text='Contact Tag', max_length=40, verbose_name='Tags'),
        ),
    ]
