# Generated by Django 4.0.6 on 2022-07-09 10:25

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('contacts', '0007_tagschoices_remove_contact_contact_tags_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TagsChoices',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='contact_tag',
        ),
        migrations.AddField(
            model_name='contact',
            name='contact_tags',
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[('NONE', ''), ('FAMILY', 'Family'), ('JOB', 'Job'), ('FRIENDS', 'Friends'),
                         ('JOURNEY', 'Journey'), ('EVENT', 'Event'), ('UNIVERSITY', 'University')],
                default=('NONE', ''), help_text='Contact Tag', max_length=40, verbose_name='Tags'),
        ),
    ]
