# Generated by Django 4.0.6 on 2022-07-10 07:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('contacts', '0009_email_linkedinurl_phonenumber_telegramnickname_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Email',
            new_name='EmailAddress',
        ),
    ]
