# Generated by Django 4.0.6 on 2022-07-10 07:26

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('contacts', '0010_rename_email_emailaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone_value',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Phone number of contact',
                                                                 max_length=13, null=True, region=None, unique=True,
                                                                 verbose_name='Phone number'),
        ),
        migrations.DeleteModel(
            name='PhoneNumber',
        ),
    ]
