# Generated by Django 4.0.6 on 2022-07-12 07:29

import django.core.validators
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('contacts', '0011_alter_contact_phone_value_delete_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone_value',
            field=phonenumber_field.modelfields.PhoneNumberField(default='', help_text='Phone number of contact',
                                                                 max_length=13, region=None, unique=True,
                                                                 verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='linkedinurl',
            name='linkedin',
            field=models.CharField(max_length=50, validators=[
                django.core.validators.URLValidator(message='Enter a link starting with "https://www.linkedin.com/in/"',
                                                    schemes='https://www.linkedin.com/in/')],
                                   verbose_name='Linkedin URL'),
        ),
        migrations.AlterField(
            model_name='telegramnickname',
            name='telegram',
            field=models.SlugField(max_length=20, verbose_name='Telegram'),
        ),
    ]
