# Generated by Django 4.1 on 2022-09-01 23:29

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("middleware_logger", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="log",
            name="last_visit",
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name="Last Visit"),
        ),
    ]
